name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/azure-frontend-deploy.yml'

env:
  AZURE_WEBAPP_NAME: customer-support-frontend
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: frontend

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug directory structure before setup
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend || echo "Frontend directory not found"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Navigate to frontend directory
        run: |
          cd frontend
          echo "Current directory after cd: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "package.json contents:"
          cat package.json

      - name: Install dependencies
        run: |
          cd frontend
          echo "Installing dependencies in: $(pwd)"
          npm install

      - name: Build
        run: |
          cd frontend
          echo "Building in: $(pwd)"
          npm run build

      - name: Verify build output
        run: |
          cd frontend
          echo "Build directory contents:"
          ls -la build/ || echo "Build directory not found"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: frontend/build 